name: Build and deploy JAR app to Azure Web App - book-store-management

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Build with Maven
        run: |
          mvn clean install -DskipTests
          echo "Build complete - listing target directory:"
          ls -l target/

      - name: Verify JAR existence
        run: |
          if [ ! -f target/*.jar ]; then
            echo "##[error]No JAR file found in target directory!"
            exit 1
          fi
          echo "JAR file found:"
          ls -l target/*.jar

      - name: Upload deployment artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: java-app
          path: ${{ github.workspace }}/deploy-artifacts

      - name: Verify downloaded artifacts
        run: |
          echo "Deployment artifacts:"
          ls -lR ${{ github.workspace }}/deploy-artifacts
          echo "JAR file path:"
          find ${{ github.workspace }}/deploy-artifacts -name "*.jar"

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_63A9ADBE0A4F4F99B04498CE830C832E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CECF7C0F14D046D0BAB6551626B4D1AC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AAFEA84F744F48668FB6B26D2E18F7C7 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'book-store-management'
          slot-name: 'Production'
          package: ${{ github.workspace }}/deploy-artifacts
          startup-command: 'java -jar /home/site/wwwroot/*.jar'

      - name: Verify deployment status
        run: |
          echo "Web App URL: ${{ steps.deploy-to-webapp.outputs.webapp-url }}"
          echo "Waiting for application startup..."
          sleep 60
          curl -I ${{ steps.deploy-to-webapp.outputs.webapp-url }}